"""ajustes das tabelas

Revision ID: e3035171eb4f
Revises: 2d797fa016a1
Create Date: 2026-06-15 21:07:43.518638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e3035171eb4f'
down_revision: Union[str, Sequence[str], None] = '2d797fa016a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fidelidade_ibfk_1', 'fidelidade', type_='foreignkey')
    op.drop_index(op.f('cliente_id'), table_name='fidelidade')
    op.drop_index(op.f('ix_fidelidade_id'), table_name='fidelidade')
    op.drop_table('fidelidade')
    op.add_column('unidades', sa.Column('ativo', sa.Boolean(), nullable=True))
    op.drop_column('unidades', 'ativa')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unidades', sa.Column('ativa', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('unidades', 'ativo')
    op.create_table('fidelidade',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cliente_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pontos', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['usuarios.id'], name=op.f('fidelidade_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_fidelidade_id'), 'fidelidade', ['id'], unique=False)
    op.create_index(op.f('cliente_id'), 'fidelidade', ['cliente_id'], unique=True)
    # ### end Alembic commands ###
